### ISSUE TITLE
Issue when installing scTyper

### ISSUE THREAD

**Issue by rgranit** [omicsCore/scTyper#4]
Hi, 

I've encountered this error while trying to install scTyper

`Error in parse(outFile) :    /tmp/RtmpJ3nr34/R.INSTALL51626827d561/scTyper/R/scTyper.R:124:42: unexpected input 123:   qc.dir <- file.path(wd, output.name, "00_qc") 124:   count.dir <- file.path(wd, output.name,　                                               ^ ERROR: unable to collate and parse R files for package ‘scTyper’ * removing ‘/home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/scTyper’ Error: Failed to install 'scTyper' from GitHub:   (converted from warning) installation of package ‘/tmp/RtmpUFVG6Z/file817f7a8d9c51/scTyper_0.1.0.tar.gz’ had non-zero exit status`

Thanks!

**Comment by darkcircle** [comment]
Hello, Dr. Granit, 
What would you use operating system? and what code did you use for doing this?
Let us know enough information to find where problem causes.
Thank you.

**Comment by rgranit** [comment]
Hi @darkcircle, 

I'm using Ubuntu 18.04 and ran the command `devtools::install_github("omicsCore/scTyper")`

Any ideas?

Thanks

**Comment by darkcircle** [comment]
Dr. Granit(@rgranit),  I tested under process from the scratch. I consider that you already have R 4.x.

1. first, I have install 5 packages provided by ubuntu official repo to support compiling R packages
```
apt-get install libxml2-dev libcurl4-openssl-dev libcairo2-dev libxt-dev jags
```
additionally, I needed to install git-lfs (to receive huge sample data from the github later)
```
apt-get install git-lfs
```

2. and I created .Renviron config file containing below 2 lines into my home directory
(of course, there is nothing to see, library path has created automatically in R console.)
```
R_LIBS_USER="~/R/x86_64-pc-linux-gnu-library/4.0"
R_LIBS_SITE="/usr/local/lib/R/site-library"
```

3. finally, I ran below many lines from R prompt, in order.
```
install.packages("devtools")
install.packages("BiocManager")
install.packages("mgcv")
install.packages("spatial")
install.packages("rjagv")

devtools::install_github("jokergoo/ComplexHeatmap")
devtools::install_github("Bioconductor/BiocGenerics")
devtools::install_github("Bioconductor/GenomicRanges")
BiocManager::install("limma")
BiocManager::install("Biobase")
BiocManager::install("infercnv")

devtools::install_github("omicsCore/scTyper")
```
Could you check please if you have something missing one?

**Comment by darkcircle** [comment]
@rgranit Have you get resolved this issue? we will close this issue after a week if above solution is fine and/or no response.

**Comment by rgranit** [comment]
@darkcircle sorry for the late reply. We followed your instructions on a 'clean' instance on the could , but unfortunately encountered this error: 

`package ‘rjagv’ is not available for this version of R` 

I suppose we can close this card and see if anyone else will encounter similar issues

Thanks!

**Comment by darkcircle** [comment]
hi, Dr. @rgranit 

> `package ‘rjagv’ is not available for this version of R`

I really concerned seriously where 'rjagv' came from. 
there are JAGS library which helps Gibbs sampling for Bayesian MCMC simulation (in short, mathematical calculation ;) ),
scTyper also uses this via 'rjags' which helps to use jags library.
so I can let you know that 'rjags' is really needed thing ('rjagv' is mistypo of 'rjags') 
It's no longer needed to do care if you have done to install 'rjags' into your machine.

please double check again by running,..

```
> install.packages('rjags')
```
and/or
```
> library(BiocManager)
> BiocManager::install('rjags')
```
then It will be done for ready to use.
Thank you.

**Comment by darkcircle** [comment]
This seems to be resolved.

closing.
